using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using Cinemachine;
using UnityEngine.SceneManagement;

public class PlayerManager : MonoBehaviour
{
    [SerializeField] GameManager gameManager;
    [SerializeField] LayerMask blockLayer;
    [SerializeField] GameObject playerDeathEffect;
    [SerializeField] ObjectShaker objectShaker;  
    [SerializeField] private AudioClip jumpsound;
    [SerializeField] private AudioClip dashsound;
    [SerializeField] private AudioClip eatsound;
    [SerializeField] private AudioClip Power;

    public enum DIRECTION_TYPE
    {
        STOP,
        RIGHT,
        LEFT,
    }

    DIRECTION_TYPE direction = DIRECTION_TYPE.STOP;

    Rigidbody2D rigidbody2DPlayer;
    AudioSource audioSource;
    GameObject mainCameraObject;
    CinemachineBrain mainCaneraObjectComponent;
    VibrationEnergyManager vibrationEnergy;
    VibrationBlockManager vibrationBlock;
   

    float speed;

    Animator animator;
    bool isRotating = false;
    bool RightArrowBlockEffect = false;
    bool UpArrowBlockEffect = false;
    bool Dash = false;
    bool VibrationEnergyUsing = false;
    bool canVibrationBlockUsing = false;
    public bool isVisualOn = false;
    private bool SongItemflag = false;
    public bool chocolate_eat = false;
    public bool chocolate_full = false;

    float jumpPower = 800;
    float sidewaysPower = 5000;
    private List<string> PushedList = new List<string>();
    private List<string> GoalPushedList = new List<string>();
    public static PlayerManager m_instance;
    public float m_magnetDistance; // ã‚³ã‚¤ãƒ³ã‚’å¼•ãã¤ã‘ã‚‹è·é›¢

    // Start is called before the first frame update
    void Start()
    {
        rigidbody2DPlayer = GetComponent<Rigidbody2D>();
        animator = GetComponent<Animator>();
        mainCameraObject = Camera.main.gameObject;
        mainCaneraObjectComponent= mainCameraObject.GetComponent<CinemachineBrain>(); 
        m_instance = this; //å¸ã„å¯„ã›ã§åˆ©ç”¨      
    }

    // Update is called once per frame
    private void Update()
    {
        float x = Input.GetAxis("Horizontal"); //ï¿½ï¿½ï¿½ï¿½ï¿½Lï¿½[ï¿½Ìæ“¾
        animator.SetFloat("speed", Mathf.Abs(x));

        if (x == 0)
        {
            direction = DIRECTION_TYPE.STOP;
        }
        else if (x > 0)
        {
            direction = DIRECTION_TYPE.RIGHT;
        }
        else if (x < 0)
        {
            direction = DIRECTION_TYPE.LEFT;
        }

        if (IsGround())
        {
            //Spaceï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ÑƒRï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[Aï¿½{ï¿½^ï¿½ï¿½
            //if (Input.GetKeyDown("space") || Input.GetKeyDown("joystick button 0"))
            if(Input.GetButtonDown("Controller button A"))
            {
                jump();
                if (SongItemflag == true)
                {
                    audioSource = GetComponent<AudioSource>();
                    audioSource.PlayOneShot(jumpsound);
                    PushedList.Add("Jump");
                    Invoke(nameof(Flagoff), 1f);
                }
            }
            else
            {
                animator.SetBool("isjumping", false);
            }
        }

        // //å¸ã„å¯„ã›èƒ½åŠ›
        // if (Input.GetKeyDown("q") && chocolate_full == false)
        //     {
        //     chocolate_eat = true;
        //     chocolate_full = true;
        //     Invoke("Eat",1.0f);
        //     Invoke("Full",10.0f);
        //     }
        // //å¸ã„å¯„ã›èƒ½åŠ›çµ‚ã‚ã‚Š

        //aï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ÑƒRï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[Xï¿½{ï¿½^ï¿½ï¿½
        //if (Input.GetKey("a") || Input.GetKey("joystick button 2"))
        if (Input.GetButton("Controller button X") )
        {
            if (SongItemflag == true && Input.GetButtonDown("Controller button X"))
            {
                audioSource = GetComponent<AudioSource>();
                Debug.Log("sound!!!");
                audioSource.PlayOneShot(dashsound);
                PushedList.Add("Dash");
                Invoke(nameof(Flagoff), 1f);
            }
            if (IsGround())
            {
                Dash = true;
            }
        }
        else
        {
            Dash = false;
        }

        //zï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ÑƒRï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[Bï¿½{ï¿½^ï¿½ï¿½
        //if ((Input.GetKeyDown("z") || Input.GetKeyDown("joystick button 1")) && isRotating == false && gameManager.canRotateflg == true)
        if (SceneManager.GetActiveScene().name == "UseRotationStage")
        {
            if ((Input.GetButtonDown("Controller button B") && isRotating == false && gameManager.canRotateflg == true))
            {
                isRotating = true;
                RightArrowBlockEffect = true;
                UpArrowBlockEffect = true;
                animator.SetBool("isrotating", true);
                Invoke("rotateCancel", 1.5f); //1.5sï¿½ï¿½É‰ï¿½]ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Zï¿½ï¿½
                gameManager.StartCoroutine("RotationCoolTimeCounterZero");

            }
        } else if (SceneManager.GetActiveScene().name == "UseHearingStage") {
            if ((Input.GetButtonDown("Controller button B") && SongItemflag == true))
            {
                audioSource = GetComponent<AudioSource>();
                audioSource.PlayOneShot(eatsound);
                PushedList.Add("Eat");
                Invoke(nameof(Flagoff), 1f);
            }
        } 

        //xï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ÑƒRï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[Yï¿½{ï¿½^ï¿½ï¿½
        //if ((Input.GetKeyDown("x") || Input.GetKeyDown("joystick button 3")) && VibrationEnergyUsing == true)
        if (SceneManager.GetActiveScene().name == "UseVibrationionStage") //ï¿½Uï¿½ï¿½ï¿½Xï¿½eï¿½[ï¿½W Todo:ï¿½lï¿½ï¿½ï¿½\ï¿½Í‚Ìƒtï¿½ï¿½ï¿½Oï¿½ÅŠÇ—ï¿½ï¿½ï¿½ï¿½ï¿½æ‚¤ï¿½ÉCï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Kï¿½vï¿½ï¿½ï¿½ï¿½
        {
            if ((Input.GetButtonDown("Controller button Y") && VibrationEnergyUsing == true))
            {
                ControllerVibrationStart();
                // StartCoroutine("TemporaryWait"); //ï¿½Rï¿½ï¿½ï¿½[ï¿½`ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÇAï¿½ï¿½ï¿½Çgï¿½í‚¸
                CinemachineOfMainCameraAndPlayerStop();
                objectShaker.Shake(mainCameraObject);
                Invoke("CinemachineOfMainCameraAndPlayerActive", 1.5f); //1,5sï¿½ï¿½É–ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ÑƒXï¿½Nï¿½ï¿½ï¿½vï¿½gï¿½ï¿½Lï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
                ReleaseVibrationEnergy(); //ï¿½ï¿½Ê“ï¿½ï¿½Ì“Gï¿½ï¿½|ï¿½ï¿½
                Invoke("ControllerVibrationEnd", 2.0f);
            }
        }else if(SceneManager.GetActiveScene().name == "UseVisualStage")
        {
            if (Input.GetButtonDown("Controller button Y"))
            {
                Debug.Log("Y");
                isVisualOn = true;
            }
                
        }else if(SceneManager.GetActiveScene().name == "UseHearingStage")
        {
            if (Input.GetButtonDown("Controller button Y") && SongItemflag == false)
            {
                SongItemflag = true;
                Invoke(nameof(SongItemflagoff), 10f);             
            }
        }else if(SceneManager.GetActiveScene().name == "UseAbsorb")
        {
            if (Input.GetButtonDown("Controller button Y") && chocolate_full == false)
            {
            chocolate_eat = true;
            chocolate_full = true;
            Invoke("Eat",1.0f);
            Invoke("Full",10.0f);
            }
        }          

        if ((Input.GetKeyDown("x") || Input.GetKeyDown("joystick button 3")) && canVibrationBlockUsing == true)
        {
            vibrationBlock.RisingBlock();
            canVibrationBlockUsing = false;
            ControllerVibrationEnd();
        }

        if(SceneManager.GetActiveScene().name == "UseHearingStage")
        {
            GoalPushedList.Add("Dash");
            GoalPushedList.Add("Jump");
            GoalPushedList.Add("Eat");

            if (PushedList.Count == 3)
            {
                if (GoalPushedList[0] == PushedList[0])
                {
                    if (GoalPushedList[1] == PushedList[1])
                    {
                        if (GoalPushedList[2] == PushedList[2])
                        {
                            audioSource.PlayOneShot(Power);
                            PushedList.Clear();
                        }
                        else
                        {
                            PushedList.Clear();
                        }
                    }
                    else
                    {
                        PushedList.Clear();
                    }
                }
                else
                {
                    PushedList.Clear();
                }
            }
        }
    }

    private void FixedUpdate()
    {
        switch (direction)
        {
            case DIRECTION_TYPE.STOP: //ï¿½~ï¿½Ü‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
                speed = 0;
                break;
            case DIRECTION_TYPE.RIGHT: //ï¿½Eï¿½É“ï¿½ï¿½ï¿½
                speed = 4;
                if(Dash)
                {
                    speed = 8;
                }
                transform.localScale = new Vector3(1, 1, 1); //ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÌŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Eï¿½É•ÏX
                break;
            case DIRECTION_TYPE.LEFT: //ï¿½ï¿½ï¿½É“ï¿½ï¿½ï¿½
                speed = -4;
                if (Dash)
                {
                    speed = -8;
                }
                transform.localScale = new Vector3(-1, 1, 1); //ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÌŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É•ÏX
                break;
        }
        rigidbody2DPlayer.velocity = new Vector2(speed, rigidbody2DPlayer.velocity.y);
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.tag == "Trap")
        {
            Destroy(this.gameObject);
            Instantiate(playerDeathEffect, this.transform.position, this.transform.rotation);
            gameManager.GameOver();
        }

        if (collision.gameObject.tag == "Item")
        {
            //ï¿½Aï¿½Cï¿½eï¿½ï¿½ï¿½æ“¾
            collision.gameObject.GetComponent<ItemManager>().GetItem();
        }

        if (collision.gameObject.tag == "HearingItem")
        {
            //ï¿½Aï¿½Cï¿½eï¿½ï¿½ï¿½æ“¾
            collision.gameObject.GetComponent<HearingHint>().GetHearingItem();
        }

        if (collision.gameObject.tag == "EnemyA")
        {
            EnemyAManager enemyA = collision.gameObject.GetComponent<EnemyAManager>();
            if (this.transform.position.y + 0.2f > enemyA.transform.position.y) //ï¿½ã‚©ï¿½ç“¥ï¿½ï¿½
            {
                rigidbody2DPlayer.velocity = new Vector2(rigidbody2DPlayer.velocity.x, 0);
                jump();
                enemyA.DestroyEnemy();
            }
            else // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô‚Â‚ï¿½ï¿½ï¿½
            {
                if (isRotating == true)
                {
                    enemyA.DestroyEnemy();
                }
                else
                {
                    Destroy(this.gameObject);
                    Instantiate(playerDeathEffect, this.transform.position, this.transform.rotation);
                    gameManager.GameOver();
                }
            }
        }

        if (collision.gameObject.tag == "EnemyB")
        {
            EnemyBManager enemyB = collision.gameObject.GetComponent<EnemyBManager>();
            if (this.transform.position.y + 0.2f > enemyB.transform.position.y) //ï¿½ã‚©ï¿½ç“¥ï¿½ï¿½
            {
                rigidbody2DPlayer.velocity = new Vector2(rigidbody2DPlayer.velocity.x, 0);
                jump();
                enemyB.DestroyEnemy();
            }
            else // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô‚Â‚ï¿½ï¿½ï¿½
            {
                if (isRotating == true)
                {
                    enemyB.DestroyEnemy();
                }
                else
                {
                    Destroy(this.gameObject);
                    Instantiate(playerDeathEffect, this.transform.position, this.transform.rotation);
                    gameManager.GameOver();
                }
            }
        }

        if (collision.gameObject.tag == "Finish")
        {
            gameManager.GameClear();
        }

        if (collision.gameObject.tag == "VibrationEnergy") //ï¿½Lï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½É“ï¿½ï¿½ï¿½ÆUï¿½ï¿½ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½
        {
            vibrationEnergy = collision.gameObject.GetComponent<VibrationEnergyManager>();
            //ControllerVibrationStart();
            VibrationEnergyUsing = true;
        }
  
    }

    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.tag == "BreakableBlock")
        {
            BreakableBlockManager breakableBlock = collision.gameObject.GetComponent<BreakableBlockManager>();

            if (isRotating == true)
            {
                breakableBlock.DestroyBreakableBlock();
            }
        }

        if (collision.gameObject.tag == "VibrationBlock")
        {
            vibrationBlock = collision.gameObject.GetComponent<VibrationBlockManager>();
            ControllerVibrationStart();
            canVibrationBlockUsing = true;
        }
    }

    private void OnTriggerStay2D(Collider2D collision)
    {

        if (collision.gameObject.tag == "UpMovingBlock")
        {
            if (isRotating == true && UpArrowBlockEffect == true)
            {
                rigidbody2DPlayer.velocity = Vector2.zero; //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½yï¿½ï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½xï¿½Æ‘ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½í‚³ï¿½ï¿½ï¿½Ä‘å‚«ï¿½ï¿½ï¿½ï¿½ï¿½Å‚ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½ï¿½ßAï¿½ï¿½ï¿½x0ï¿½Åï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                rigidbody2DPlayer.AddForce(Vector2.up * jumpPower * 2);
                UpArrowBlockEffect = false;
            }
        }

        if (collision.gameObject.tag == "RightMovingBlock")
        {
            if (isRotating == true && RightArrowBlockEffect == true)
            {
                rigidbody2DPlayer.velocity = Vector2.zero; //xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‘ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Æ‘ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½í‚³ï¿½ï¿½ï¿½Ä‘å‚«ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½ï¿½ßAï¿½ï¿½ï¿½x0ï¿½Åï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                rigidbody2DPlayer.AddForce(Vector2.right * sidewaysPower * 2);
                RightArrowBlockEffect = false;
            }
        }
    }
    
    private void OnTriggerExit2D(Collider2D collision) //ï¿½Lï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ÆUï¿½ï¿½ï¿½ï¿½ï¿½~ï¿½ß‚ï¿½
    {
        if (collision.gameObject.tag == "VibrationEnergy")
        {
            VibrationEnergyUsing = false;
            //ControllerVibrationEnd();
        }
    }

    private void OnCollisionExit2D(Collision2D collision)
    {
        if (collision.gameObject.tag == "VibrationBlock")
        {
            vibrationBlock = collision.gameObject.GetComponent<VibrationBlockManager>();
            ControllerVibrationEnd();
            canVibrationBlockUsing = false;
        }
    }


    // ===================================================================================================================================
    // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ÊŠÖï¿½ï¿½QStart
    // ===================================================================================================================================

    /// <summary>
    /// ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    /// </summary>
    void jump()
    {
        //ï¿½ï¿½É—Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        rigidbody2DPlayer.AddForce(Vector2.up * jumpPower);
        animator.SetBool("isjumping", true);

    }
    

   /// <summary>
   /// ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Æ’nï¿½Ê‚Ìİ’uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½
   /// </summary>
    bool IsGround()
    {
        //ï¿½nï¿½_ï¿½ÆIï¿½_ï¿½ï¿½ï¿½ì¬
        Vector3 leftStartPoint = transform.position - Vector3.right * 0.2f + Vector3.up * 0.04f;
        Vector3 rightStartPoint = transform.position + Vector3.right * 0.2f + Vector3.up * 0.04f;
        Vector3 endPoint = transform.position - Vector3.up * 0.1f;
        //Debug.DrawLine(leftStartPoint, endPoint);
        //Debug.DrawLine(rightStartPoint, endPoint);
        return Physics2D.Linecast(leftStartPoint, endPoint, blockLayer)
            || Physics2D.Linecast(rightStartPoint, endPoint, blockLayer);
    }

    /// <summary>
    /// ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[ï¿½ÌUï¿½ï¿½ï¿½ï¿½ï¿½Jï¿½nï¿½ï¿½ï¿½ï¿½
    /// </summary>

    void ControllerVibrationStart()
    {
        Gamepad gamepad = Gamepad.current;
        if (gamepad != null)
        {
            gamepad.SetMotorSpeeds(0.5f, 1.0f);
        }
    }

    /// <summary>
    /// ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[ï¿½ÌUï¿½ï¿½ï¿½ï¿½ï¿½~ï¿½ß‚ï¿½
    /// </summary>
    void ControllerVibrationEnd()
    {
        Gamepad gamepad = Gamepad.current;
        if (gamepad != null)
        {
            gamepad.SetMotorSpeeds(0.0f, 0.0f);
        }
    }

    /// <summary>
    /// MainCameraï¿½ï¿½ChinemachineBrainï¿½Æ‚ï¿½ï¿½ÌƒXï¿½Nï¿½ï¿½ï¿½vï¿½gï¿½ï¿½ï¿½gï¿½ï¿½ï¿½Aï¿½Nï¿½eï¿½Bï¿½uï¿½É‚ï¿½ï¿½ï¿½
    /// </summary>
    void CinemachineOfMainCameraAndPlayerActive()
    {
        mainCaneraObjectComponent.enabled = true;
        this.enabled = true;

    }

    /// <summary>
    /// MainCameraï¿½ï¿½ChinemachineBrainï¿½Æ‚ï¿½ï¿½ê©ï¿½gï¿½ï¿½ï¿½Aï¿½Nï¿½eï¿½Bï¿½uï¿½É‚ï¿½ï¿½ï¿½
    /// </summary>
    void CinemachineOfMainCameraAndPlayerStop()
    {
        mainCaneraObjectComponent.enabled = false; //ChinemachineBrainï¿½ğ–³Œï¿½
        animator.SetFloat("speed", Mathf.Abs(0));  
        rigidbody2DPlayer.velocity = new Vector2(0, rigidbody2DPlayer.velocity.y); //ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½ï¿½Mï¿½~ï¿½bï¿½Nï¿½ğ”­“ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½ï¿½ï¿½lï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½Åƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ì“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½~ï¿½ß‚ï¿½
        this.enabled = false; //ï¿½ï¿½ï¿½ÌƒXï¿½Nï¿½ï¿½ï¿½vï¿½gï¿½ğ–³Œï¿½ï¿½É‚ï¿½ï¿½Äƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ğ“®‚ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½ï¿½
    }

    // ===================================================================================================================================
    // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ÊŠÖï¿½ï¿½QEnd
    // ===================================================================================================================================

    // ===================================================================================================================================
    // ï¿½ï¿½]ï¿½Xï¿½eï¿½[ï¿½Wï¿½Öï¿½ï¿½QStart
    // ===================================================================================================================================

    /// <summary>
    /// ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ì‰ï¿½]ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Zï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iInvokeï¿½ÅŒÄ‚Ñoï¿½ï¿½ï¿½Ägï¿½pï¿½j
    /// </summary>
    private void rotateCancel()
    {
        if (isRotating)
        {
            isRotating = false;
            animator.SetBool("isrotating", false);
            //gameManager.RotationCoolTimeCounterZero();       
        }
    }

    // ===================================================================================================================================
    // ï¿½ï¿½]ï¿½Xï¿½eï¿½[ï¿½Wï¿½Öï¿½ï¿½QEnd
    // ===================================================================================================================================

    // ===================================================================================================================================
    // ï¿½Uï¿½ï¿½ï¿½Xï¿½eï¿½[ï¿½Wï¿½Öï¿½ï¿½QStart
    // ===================================================================================================================================

    /// <summary>
    /// ï¿½ï¿½ï¿½Í‚ÌƒRï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½ï¿½ï¿½Wï¿½ß‚ÄAï¿½Gï¿½ÌƒRï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½Å‚ï¿½ï¿½ï¿½Î‚ï¿½ï¿½Ì“Gï¿½ï¿½|ï¿½ï¿½
    /// </summary>
    private void ReleaseVibrationEnergy()
    {
        Collider2D[] enemyCols = Physics2D.OverlapBoxAll(transform.position, new Vector2(18.0f, 10.0f), 0.0f);
        if (enemyCols != null)
        {
            for (int i = 0; i < enemyCols.Length; i++)
            {
                EnemyAManager enemy = enemyCols[i].GetComponent<EnemyAManager>();
                if (enemy != null)
                {

                    enemy.DestroyEnemy();
                }
            }
        }

        if (vibrationEnergy != null) vibrationEnergy.OnCompleteEffect(); //ï¿½Lï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½Gï¿½tï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        VibrationEnergyUsing = false; //ï¿½Aï¿½Å–hï¿½~
    }

    /// <summary>
    /// ï¿½êï¿½Iï¿½Éƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ğ“®‚ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½ï¿½
    /// </summary>
        private IEnumerator TemporaryWait()
    {
        ControllerVibrationStart();
        yield return new WaitForSeconds(1.0f);
        CinemachineOfMainCameraAndPlayerStop();
        objectShaker.Shake(mainCameraObject);
        Invoke("CinemachineOfMainCameraAndPlayerActive", 1.5f); //1,5sï¿½ï¿½É–ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ÑƒXï¿½Nï¿½ï¿½ï¿½vï¿½gï¿½ï¿½Lï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
        ReleaseVibrationEnergy(); //ï¿½ï¿½Ê“ï¿½ï¿½Ì“Gï¿½ï¿½|ï¿½ï¿½
        Invoke("ControllerVibrationEnd", 1.5f);
    }

    // ===================================================================================================================================
    // ï¿½Uï¿½ï¿½ï¿½Xï¿½eï¿½[ï¿½Wï¿½Öï¿½ï¿½QEnd
    // ===================================================================================================================================

    // ===================================================================================================================================
    // ï¿½ï¿½ï¿½oï¿½Xï¿½eï¿½[ï¿½Wï¿½Öï¿½ï¿½QStart
    // ===================================================================================================================================

    void Flagoff()
    {
        PushedList.Clear();
    }

    void SongItemflagoff()
    {
        SongItemflag = false;
    }

    // ===================================================================================================================================
    // ï¿½ï¿½ï¿½oï¿½Xï¿½eï¿½[ï¿½Wï¿½Öï¿½ï¿½QEnd
    // ===================================================================================================================================



    // ===================================================================================================================================
    // StartAbsorb
    // ===================================================================================================================================

    void Eat()
    {
        chocolate_eat = false;
    }

    void Full()
    {
        chocolate_full = false;
    }

    // ===================================================================================================================================
    // EndAbsorb
    // ===================================================================================================================================




}
